### ISSUE TITLE
Nasty timeout bug between SOTAMAT and SOTACAT

### ISSUE THREAD

**Issue by jeffkowalski** [SOTAmat/SOTAcat#9] opened 2024-02-22 04:16 UTC
Per Brian:  I think I need to debug this as it is likely in the Xamarin code.
Duplicate of #3?

**Comment by jeffkowalski** [comment] 2024-02-22 04:25
@brianmathews, would you kindly comment on whether this is a dup of #3 ?

**Comment by brianmathews** [comment] 2024-02-22 05:23
Yes. This is a duplicate of #3.
Closing.

**Closed by brianmathews** 2024-02-22 05:23 UTC
Labels: bug
